version: 2.1
jobs:
  build:
    docker: #执行容器
      - image: circleci/node:10 #依赖环境
    branches: #分支
      only:
      - master
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - add_ssh_keys:
          fingerprints:
            - '6e:9e:a8:9c:36:9e:24:a3:f2:a7:e7:cc:0b:2c:25:eb'  # 这个就是添加ssh key生成的指纹id，将其复制到这里即可
      - checkout # 从githun拉去代码
      # 使用缓存
      - restore_cache:
          key: node-dependens # 这个key和save_cache的key相对应，表示使用的是这个key对应的缓存
      - run: 
          name: Install
          command: yarn install
      # 设置缓存
      - save_cache:
          key: node-dependens
          paths:
            - node_modules
      - run:
          name: Build
          command: yarn build